Fix -Wdeprecated warnings due to Expectation's user-provided destructor. NFC.
/home/travis/build/Quuxplusone/googletest/googlemock/include/gmock/gmock-spec-builders.h:503:3: error:
      definition of implicit copy constructor for 'Expectation' is deprecated
      because it has a user-declared destructor [-Werror,-Wdeprecated]
  ~Expectation();
  ^
/home/travis/build/Quuxplusone/googletest/googlemock/src/gmock-spec-builders.cc:496:14: note:
      implicit copy constructor for 'Expectation' first required here
      return Expectation(*it);
             ^
/home/travis/build/Quuxplusone/googletest/googlemock/src/gmock-spec-builders.cc:854:14: error:
      definition of implicit copy assignment operator for 'Expectation' is
      deprecated because it has a user-declared destructor
      [-Werror,-Wdeprecated]
Expectation::~Expectation() {}
             ^
/home/travis/build/Quuxplusone/googletest/googlemock/src/gmock-spec-builders.cc:863:24: note:
      implicit copy assignment operator for 'Expectation' first required here
    *last_expectation_ = expectation;
                       ^