Fix unused function warning on Mac OS.
As of recently, Google Test fails to compile with the warning below when
used in projects with strict warning settings.

googletest/src/gtest-death-test.cc:1004:13: error: unused function 'StackGrowsDown' [-Werror,-Wunused-function]