Fix -Wdeprecated warnings in this test. NFC.
/home/travis/build/Quuxplusone/googletest/googletest/test/googletest-param-test-test.cc:502:8: error:
      definition of implicit copy constructor for
      'NonDefaultConstructAssignString' is deprecated because it has a
      user-declared copy assignment operator [-Werror,-Wdeprecated]
  void operator=(const NonDefaultConstructAssignString&);
       ^
/home/travis/build/Quuxplusone/googletest/googletest/test/googletest-param-test-test.cc:507:36: note:
      implicit copy constructor for 'NonDefaultConstructAssignString' first
      required here
      Combine(Values(0, 1), Values(NonDefaultConstructAssignString("A"),
                                   ^