Eliminate all uses of the GTEST_DISALLOW_* macros, and remove them.
For the user-facing classes `Test`, `TestSuite`, etc., where there were
explicit C++ comments saying that we delete the special members, I added
the deleted special member declarations by hand.

For `VariadicMatcher`, we actually NEED to cut short the compiler's
deliberations about whether the type is copyable, because if we don't,
it recurses down into the `std::tuple` and triggers Clang's error
"recursive template instantiation exceeded maximum depth of 256".
However, `VariadicMatcher` does need to be copy-constructible, so
we default its copy constructor (to avoid `-Wdeprecated-copy`, see below).

For every other case, where these are internal implementation details
that nobody in their right mind would ever try to do value semantics with,
I just removed the deleted members, following the Rule of Zero.

This commit fixes all Clang trunk's warnings about `-Wdeprecated-copy`,
for example:

    /home/travis/build/Quuxplusone/googletest/googlemock/include/gmock/gmock-actions.h:579:3: error:
          definition of implicit copy constructor for
          'PolymorphicAction<testing::internal::ReturnNullAction>' is deprecated
          because it has a user-declared copy assignment operator
          [-Werror,-Wdeprecated]
      GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
      ^
    /home/travis/build/Quuxplusone/googletest/googletest/include/gtest/internal/gtest-port.h:679:9: note:
          expanded from macro 'GTEST_DISALLOW_ASSIGN_'
      type& operator=(type const &) = delete
            ^
    /home/travis/build/Quuxplusone/googletest/googlemock/include/gmock/gmock-actions.h:1166:10: note:
          implicit copy constructor for
          'PolymorphicAction<testing::internal::ReturnNullAction>' first required
          here
      return MakePolymorphicAction(internal::ReturnNullAction());
             ^

and:

    /home/travis/build/Quuxplusone/googletest/googlemock/test/gmock-spec-builders_test.cc:1883:1: error:
          definition of implicit copy constructor for 'DeleteActionP<(anonymous
          namespace)::MockA *>' is deprecated because it has a user-declared copy
          assignment operator [-Werror,-Wdeprecated]
    ACTION_P(Delete, ptr) { delete ptr; }
    ^