Fix -Wdeprecated warning in this test code. NFC.
/home/travis/build/Quuxplusone/googletest/googletest/test/googletest-port-test.cc:97:11: error:
      definition of implicit copy constructor for 'Base' is deprecated because
      it has a user-declared destructor [-Werror,-Wdeprecated]
  virtual ~Base() {}
          ^
/home/travis/build/Quuxplusone/googletest/googletest/test/googletest-port-test.cc:116:56: note:
      implicit copy constructor for 'Base' first required here
  Base base = ::testing::internal::ImplicitCast_<Base>(derived);
                                                       ^