Get DoubleNearPredFormat to fail on bad epsilons
DoubleNearPredFormat will happily accept epsilon values (abs_error) that
are so small that they are meaningless. This turns EXPECT_NEAR into a
complicated and non-obvious version of EXPECT_EQUAL.

This change modifies DoubleNearPredFormat) to calculate the smallest
meaningful epsilon value, given the input values, and then fail if
abs_error is smaller than that.

With this change the flaky test mentioned in crbug.com/786046 goes from
a flaky test to this 100% reliable failure:

../../base/time/time_win_unittest.cc(292): error: The epsilon used to
compare expected_microseconds_since_origin and
converted_microseconds_since_origin is less than the minimum epsilon in
this range, which is 512, where
expected_microseconds_since_origin evaluates to 3.640989196237484e+18,
converted_microseconds_since_origin evaluates to 3.640989196237484e+18, and
1.0 evaluates to 1.
ticks=9223372036854775807, to be converted via logic path: SAFE

This fixes issue #1350